services:
  dms-api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: dms-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - dms-db

  dms-db:
    image: postgres:13
    container_name: dms-db
    environment:
      POSTGRES_USER: dmsuser
      POSTGRES_PASSWORD: dmspassword
      POSTGRES_DB: dmsdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
