services:
  rest_api:
    image: rest_api_image
    build:
      context: .
      dockerfile: ./REST_API/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080/
    depends_on:
      - dms-db
      - rabbitmq
    restart: unless-stopped

  dms-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dmsuser
      POSTGRES_PASSWORD: dmspassword
      POSTGRES_DB: dmsdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  webui:
    image: web_ui_image
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./WebUI/nginx.conf:/etc/nginx/nginx.conf  # Bind the Nginx configuration file
      - ./WebUI/wwwroot:/app/wwwroot  # Mount static files
    depends_on:
      - rest_api

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"    # RabbitMQ broker port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db-data:
