services:
  rest_api:
    image: rest_api
    build:
      context: ./REST_API
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080/
    # depends_on:
    #   - dms-db

  # dms-db:
  #   image: db_image
  #   environment:
  #     POSTGRES_USER: dmsuser
  #     POSTGRES_PASSWORD: dmspassword
  #     POSTGRES_DB: dmsdb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

  webui:
    image: webui_api_image
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./WebUI/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./WebUI/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
      - rest_api


volumes:
  db-data:
  
  
